// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plugin/common.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MapEntry represents a single key-value pair in a map.
type MapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEntry) Reset() {
	*x = MapEntry{}
	mi := &file_plugin_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEntry) ProtoMessage() {}

func (x *MapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEntry.ProtoReflect.Descriptor instead.
func (*MapEntry) Descriptor() ([]byte, []int) {
	return file_plugin_common_proto_rawDescGZIP(), []int{0}
}

func (x *MapEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MapValue represents a map of string key-value pairs.
type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MapEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_plugin_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_plugin_common_proto_rawDescGZIP(), []int{1}
}

func (x *MapValue) GetEntries() []*MapEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_plugin_common_proto protoreflect.FileDescriptor

const file_plugin_common_proto_rawDesc = "" +
	"\n" +
	"\x13plugin/common.proto\x12\rwv2ray.plugin\"2\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"=\n" +
	"\bMapValue\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.wv2ray.plugin.MapEntryR\aentriesB\x15Z\x13wv2ray/proto/pluginb\x06proto3"

var (
	file_plugin_common_proto_rawDescOnce sync.Once
	file_plugin_common_proto_rawDescData []byte
)

func file_plugin_common_proto_rawDescGZIP() []byte {
	file_plugin_common_proto_rawDescOnce.Do(func() {
		file_plugin_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_common_proto_rawDesc), len(file_plugin_common_proto_rawDesc)))
	})
	return file_plugin_common_proto_rawDescData
}

var file_plugin_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_common_proto_goTypes = []any{
	(*MapEntry)(nil), // 0: wv2ray.plugin.MapEntry
	(*MapValue)(nil), // 1: wv2ray.plugin.MapValue
}
var file_plugin_common_proto_depIdxs = []int32{
	0, // 0: wv2ray.plugin.MapValue.entries:type_name -> wv2ray.plugin.MapEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_common_proto_init() }
func file_plugin_common_proto_init() {
	if File_plugin_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_common_proto_rawDesc), len(file_plugin_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_common_proto_goTypes,
		DependencyIndexes: file_plugin_common_proto_depIdxs,
		MessageInfos:      file_plugin_common_proto_msgTypes,
	}.Build()
	File_plugin_common_proto = out.File
	file_plugin_common_proto_goTypes = nil
	file_plugin_common_proto_depIdxs = nil
}
