// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plugin/mux.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MuxSetting represents the multiplexing settings for a connection.
type MuxSetting struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Concurrency     int64                  `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	XudpConcurrency int64                  `protobuf:"varint,3,opt,name=xudp_concurrency,json=xudpConcurrency,proto3" json:"xudp_concurrency,omitempty"`
	XudpProxyUdp443 string                 `protobuf:"bytes,4,opt,name=xudp_proxy_udp443,json=xudpProxyUdp443,proto3" json:"xudp_proxy_udp443,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MuxSetting) Reset() {
	*x = MuxSetting{}
	mi := &file_plugin_mux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuxSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuxSetting) ProtoMessage() {}

func (x *MuxSetting) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_mux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuxSetting.ProtoReflect.Descriptor instead.
func (*MuxSetting) Descriptor() ([]byte, []int) {
	return file_plugin_mux_proto_rawDescGZIP(), []int{0}
}

func (x *MuxSetting) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MuxSetting) GetConcurrency() int64 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *MuxSetting) GetXudpConcurrency() int64 {
	if x != nil {
		return x.XudpConcurrency
	}
	return 0
}

func (x *MuxSetting) GetXudpProxyUdp443() string {
	if x != nil {
		return x.XudpProxyUdp443
	}
	return ""
}

var File_plugin_mux_proto protoreflect.FileDescriptor

const file_plugin_mux_proto_rawDesc = "" +
	"\n" +
	"\x10plugin/mux.proto\x12\rwv2ray.plugin\"\x9f\x01\n" +
	"\n" +
	"MuxSetting\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x03R\vconcurrency\x12)\n" +
	"\x10xudp_concurrency\x18\x03 \x01(\x03R\x0fxudpConcurrency\x12*\n" +
	"\x11xudp_proxy_udp443\x18\x04 \x01(\tR\x0fxudpProxyUdp443B\x15Z\x13wv2ray/proto/pluginb\x06proto3"

var (
	file_plugin_mux_proto_rawDescOnce sync.Once
	file_plugin_mux_proto_rawDescData []byte
)

func file_plugin_mux_proto_rawDescGZIP() []byte {
	file_plugin_mux_proto_rawDescOnce.Do(func() {
		file_plugin_mux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_mux_proto_rawDesc), len(file_plugin_mux_proto_rawDesc)))
	})
	return file_plugin_mux_proto_rawDescData
}

var file_plugin_mux_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_plugin_mux_proto_goTypes = []any{
	(*MuxSetting)(nil), // 0: wv2ray.plugin.MuxSetting
}
var file_plugin_mux_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_mux_proto_init() }
func file_plugin_mux_proto_init() {
	if File_plugin_mux_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_mux_proto_rawDesc), len(file_plugin_mux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_mux_proto_goTypes,
		DependencyIndexes: file_plugin_mux_proto_depIdxs,
		MessageInfos:      file_plugin_mux_proto_msgTypes,
	}.Build()
	File_plugin_mux_proto = out.File
	file_plugin_mux_proto_goTypes = nil
	file_plugin_mux_proto_depIdxs = nil
}
