// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plugin/outbound.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginOutboundConfig represents the configuration for an outbound plugin.
type PluginOutboundConfig struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Protocol      string                   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Address       string                   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Name          string                   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Properties    []*BriefProtocolProperty `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginOutboundConfig) Reset() {
	*x = PluginOutboundConfig{}
	mi := &file_plugin_outbound_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginOutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOutboundConfig) ProtoMessage() {}

func (x *PluginOutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_outbound_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOutboundConfig.ProtoReflect.Descriptor instead.
func (*PluginOutboundConfig) Descriptor() ([]byte, []int) {
	return file_plugin_outbound_proto_rawDescGZIP(), []int{0}
}

func (x *PluginOutboundConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PluginOutboundConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PluginOutboundConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PluginOutboundConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginOutboundConfig) GetProperties() []*BriefProtocolProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_plugin_outbound_proto protoreflect.FileDescriptor

const file_plugin_outbound_proto_rawDesc = "" +
	"\n" +
	"\x15plugin/outbound.proto\x12\rwv2ray.plugin\x1a\x1fplugin/protocol_configuer.proto\"\xba\x01\n" +
	"\x14PluginOutboundConfig\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12D\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2$.wv2ray.plugin.BriefProtocolPropertyR\n" +
	"propertiesB\x15Z\x13wv2ray/proto/pluginb\x06proto3"

var (
	file_plugin_outbound_proto_rawDescOnce sync.Once
	file_plugin_outbound_proto_rawDescData []byte
)

func file_plugin_outbound_proto_rawDescGZIP() []byte {
	file_plugin_outbound_proto_rawDescOnce.Do(func() {
		file_plugin_outbound_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_outbound_proto_rawDesc), len(file_plugin_outbound_proto_rawDesc)))
	})
	return file_plugin_outbound_proto_rawDescData
}

var file_plugin_outbound_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_plugin_outbound_proto_goTypes = []any{
	(*PluginOutboundConfig)(nil),  // 0: wv2ray.plugin.PluginOutboundConfig
	(*BriefProtocolProperty)(nil), // 1: wv2ray.plugin.BriefProtocolProperty
}
var file_plugin_outbound_proto_depIdxs = []int32{
	1, // 0: wv2ray.plugin.PluginOutboundConfig.properties:type_name -> wv2ray.plugin.BriefProtocolProperty
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_outbound_proto_init() }
func file_plugin_outbound_proto_init() {
	if File_plugin_outbound_proto != nil {
		return
	}
	file_plugin_protocol_configuer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_outbound_proto_rawDesc), len(file_plugin_outbound_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_outbound_proto_goTypes,
		DependencyIndexes: file_plugin_outbound_proto_depIdxs,
		MessageInfos:      file_plugin_outbound_proto_msgTypes,
	}.Build()
	File_plugin_outbound_proto = out.File
	file_plugin_outbound_proto_goTypes = nil
	file_plugin_outbound_proto_depIdxs = nil
}
