// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plugin/protocol_configuer.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigFieldType defines the type of a configuration field.
type ConfigFieldType int32

const (
	ConfigFieldType_INPUT  ConfigFieldType = 0
	ConfigFieldType_SELECT ConfigFieldType = 1
)

// Enum value maps for ConfigFieldType.
var (
	ConfigFieldType_name = map[int32]string{
		0: "INPUT",
		1: "SELECT",
	}
	ConfigFieldType_value = map[string]int32{
		"INPUT":  0,
		"SELECT": 1,
	}
)

func (x ConfigFieldType) Enum() *ConfigFieldType {
	p := new(ConfigFieldType)
	*p = x
	return p
}

func (x ConfigFieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigFieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_protocol_configuer_proto_enumTypes[0].Descriptor()
}

func (ConfigFieldType) Type() protoreflect.EnumType {
	return &file_plugin_protocol_configuer_proto_enumTypes[0]
}

func (x ConfigFieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigFieldType.Descriptor instead.
func (ConfigFieldType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{0}
}

// ConfigFieldValueType defines the value type of a configuration field.
type ConfigFieldValueType int32

const (
	ConfigFieldValueType_STRING ConfigFieldValueType = 0
	ConfigFieldValueType_INT    ConfigFieldValueType = 1
	ConfigFieldValueType_BOOL   ConfigFieldValueType = 2
	ConfigFieldValueType_MAP    ConfigFieldValueType = 3
)

// Enum value maps for ConfigFieldValueType.
var (
	ConfigFieldValueType_name = map[int32]string{
		0: "STRING",
		1: "INT",
		2: "BOOL",
		3: "MAP",
	}
	ConfigFieldValueType_value = map[string]int32{
		"STRING": 0,
		"INT":    1,
		"BOOL":   2,
		"MAP":    3,
	}
)

func (x ConfigFieldValueType) Enum() *ConfigFieldValueType {
	p := new(ConfigFieldValueType)
	*p = x
	return p
}

func (x ConfigFieldValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigFieldValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_protocol_configuer_proto_enumTypes[1].Descriptor()
}

func (ConfigFieldValueType) Type() protoreflect.EnumType {
	return &file_plugin_protocol_configuer_proto_enumTypes[1]
}

func (x ConfigFieldValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigFieldValueType.Descriptor instead.
func (ConfigFieldValueType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{1}
}

// ConfigFieldValue represents the value of a configuration field.
type ConfigFieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ConfigFieldValue_StrValue
	//	*ConfigFieldValue_IntValue
	//	*ConfigFieldValue_BoolValue
	//	*ConfigFieldValue_MapValue
	Value         isConfigFieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFieldValue) Reset() {
	*x = ConfigFieldValue{}
	mi := &file_plugin_protocol_configuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFieldValue) ProtoMessage() {}

func (x *ConfigFieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_protocol_configuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFieldValue.ProtoReflect.Descriptor instead.
func (*ConfigFieldValue) Descriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigFieldValue) GetValue() isConfigFieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigFieldValue) GetStrValue() string {
	if x != nil {
		if x, ok := x.Value.(*ConfigFieldValue_StrValue); ok {
			return x.StrValue
		}
	}
	return ""
}

func (x *ConfigFieldValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*ConfigFieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *ConfigFieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ConfigFieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ConfigFieldValue) GetMapValue() *MapValue {
	if x != nil {
		if x, ok := x.Value.(*ConfigFieldValue_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

type isConfigFieldValue_Value interface {
	isConfigFieldValue_Value()
}

type ConfigFieldValue_StrValue struct {
	StrValue string `protobuf:"bytes,1,opt,name=str_value,json=strValue,proto3,oneof"`
}

type ConfigFieldValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ConfigFieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ConfigFieldValue_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,4,opt,name=map_value,json=mapValue,proto3,oneof"`
}

func (*ConfigFieldValue_StrValue) isConfigFieldValue_Value() {}

func (*ConfigFieldValue_IntValue) isConfigFieldValue_Value() {}

func (*ConfigFieldValue_BoolValue) isConfigFieldValue_Value() {}

func (*ConfigFieldValue_MapValue) isConfigFieldValue_Value() {}

// SelectOption represents an option for selection-type configuration fields.
type SelectOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Label string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*SelectOption_StrValue
	//	*SelectOption_IntValue
	Value         isSelectOption_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOption) Reset() {
	*x = SelectOption{}
	mi := &file_plugin_protocol_configuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOption) ProtoMessage() {}

func (x *SelectOption) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_protocol_configuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOption.ProtoReflect.Descriptor instead.
func (*SelectOption) Descriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{1}
}

func (x *SelectOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SelectOption) GetValue() isSelectOption_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SelectOption) GetStrValue() string {
	if x != nil {
		if x, ok := x.Value.(*SelectOption_StrValue); ok {
			return x.StrValue
		}
	}
	return ""
}

func (x *SelectOption) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*SelectOption_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

type isSelectOption_Value interface {
	isSelectOption_Value()
}

type SelectOption_StrValue struct {
	StrValue string `protobuf:"bytes,2,opt,name=str_value,json=strValue,proto3,oneof"`
}

type SelectOption_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*SelectOption_StrValue) isSelectOption_Value() {}

func (*SelectOption_IntValue) isSelectOption_Value() {}

// ProtocolConfigProperty represents a configuration property for a protocol.
type ProtocolConfigProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	FieldLabel    string                 `protobuf:"bytes,2,opt,name=field_label,json=fieldLabel,proto3" json:"field_label,omitempty"`
	FieldType     ConfigFieldType        `protobuf:"varint,3,opt,name=field_type,json=fieldType,proto3,enum=wv2ray.plugin.ConfigFieldType" json:"field_type,omitempty"`
	ValueType     ConfigFieldValueType   `protobuf:"varint,4,opt,name=value_type,json=valueType,proto3,enum=wv2ray.plugin.ConfigFieldValueType" json:"value_type,omitempty"`
	Value         *ConfigFieldValue      `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Required      bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	Options       []*SelectOption        `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	DefaultValue  *ConfigFieldValue      `protobuf:"bytes,8,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolConfigProperty) Reset() {
	*x = ProtocolConfigProperty{}
	mi := &file_plugin_protocol_configuer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolConfigProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolConfigProperty) ProtoMessage() {}

func (x *ProtocolConfigProperty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_protocol_configuer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolConfigProperty.ProtoReflect.Descriptor instead.
func (*ProtocolConfigProperty) Descriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{2}
}

func (x *ProtocolConfigProperty) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ProtocolConfigProperty) GetFieldLabel() string {
	if x != nil {
		return x.FieldLabel
	}
	return ""
}

func (x *ProtocolConfigProperty) GetFieldType() ConfigFieldType {
	if x != nil {
		return x.FieldType
	}
	return ConfigFieldType_INPUT
}

func (x *ProtocolConfigProperty) GetValueType() ConfigFieldValueType {
	if x != nil {
		return x.ValueType
	}
	return ConfigFieldValueType_STRING
}

func (x *ProtocolConfigProperty) GetValue() *ConfigFieldValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProtocolConfigProperty) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ProtocolConfigProperty) GetOptions() []*SelectOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ProtocolConfigProperty) GetDefaultValue() *ConfigFieldValue {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

// ProtocolConfigProperties represents a collection of ProtocolConfigProperty messages.
type ProtocolConfigProperties struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Properties    []*ProtocolConfigProperty `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolConfigProperties) Reset() {
	*x = ProtocolConfigProperties{}
	mi := &file_plugin_protocol_configuer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolConfigProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolConfigProperties) ProtoMessage() {}

func (x *ProtocolConfigProperties) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_protocol_configuer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolConfigProperties.ProtoReflect.Descriptor instead.
func (*ProtocolConfigProperties) Descriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{3}
}

func (x *ProtocolConfigProperties) GetProperties() []*ProtocolConfigProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

// ProtocolConfigDetail represents the configuration details for a specific protocol.
type ProtocolConfigDetail struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Protocol      string                    `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Properties    *ProtocolConfigProperties `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolConfigDetail) Reset() {
	*x = ProtocolConfigDetail{}
	mi := &file_plugin_protocol_configuer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolConfigDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolConfigDetail) ProtoMessage() {}

func (x *ProtocolConfigDetail) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_protocol_configuer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolConfigDetail.ProtoReflect.Descriptor instead.
func (*ProtocolConfigDetail) Descriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{4}
}

func (x *ProtocolConfigDetail) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolConfigDetail) GetProperties() *ProtocolConfigProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

// ProtocolConfigList represents a list of protocol configuration details.
type ProtocolConfigList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Protocols     []*ProtocolConfigDetail `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolConfigList) Reset() {
	*x = ProtocolConfigList{}
	mi := &file_plugin_protocol_configuer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolConfigList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolConfigList) ProtoMessage() {}

func (x *ProtocolConfigList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_protocol_configuer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolConfigList.ProtoReflect.Descriptor instead.
func (*ProtocolConfigList) Descriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{5}
}

func (x *ProtocolConfigList) GetProtocols() []*ProtocolConfigDetail {
	if x != nil {
		return x.Protocols
	}
	return nil
}

// BriefProtocolProperty represents a brief configuration property with only field and value.
type BriefProtocolProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         *ConfigFieldValue      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BriefProtocolProperty) Reset() {
	*x = BriefProtocolProperty{}
	mi := &file_plugin_protocol_configuer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BriefProtocolProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BriefProtocolProperty) ProtoMessage() {}

func (x *BriefProtocolProperty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_protocol_configuer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BriefProtocolProperty.ProtoReflect.Descriptor instead.
func (*BriefProtocolProperty) Descriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{6}
}

func (x *BriefProtocolProperty) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *BriefProtocolProperty) GetValue() *ConfigFieldValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// BriefProtocolProperties represents a collection of brief protocol properties.
type BriefProtocolProperties struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Properties    []*BriefProtocolProperty `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BriefProtocolProperties) Reset() {
	*x = BriefProtocolProperties{}
	mi := &file_plugin_protocol_configuer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BriefProtocolProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BriefProtocolProperties) ProtoMessage() {}

func (x *BriefProtocolProperties) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_protocol_configuer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BriefProtocolProperties.ProtoReflect.Descriptor instead.
func (*BriefProtocolProperties) Descriptor() ([]byte, []int) {
	return file_plugin_protocol_configuer_proto_rawDescGZIP(), []int{7}
}

func (x *BriefProtocolProperties) GetProperties() []*BriefProtocolProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_plugin_protocol_configuer_proto protoreflect.FileDescriptor

const file_plugin_protocol_configuer_proto_rawDesc = "" +
	"\n" +
	"\x1fplugin/protocol_configuer.proto\x12\rwv2ray.plugin\x1a\x13plugin/common.proto\"\xb2\x01\n" +
	"\x10ConfigFieldValue\x12\x1d\n" +
	"\tstr_value\x18\x01 \x01(\tH\x00R\bstrValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x126\n" +
	"\tmap_value\x18\x04 \x01(\v2\x17.wv2ray.plugin.MapValueH\x00R\bmapValueB\a\n" +
	"\x05value\"k\n" +
	"\fSelectOption\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1d\n" +
	"\tstr_value\x18\x02 \x01(\tH\x00R\bstrValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValueB\a\n" +
	"\x05value\"\xa2\x03\n" +
	"\x16ProtocolConfigProperty\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1f\n" +
	"\vfield_label\x18\x02 \x01(\tR\n" +
	"fieldLabel\x12=\n" +
	"\n" +
	"field_type\x18\x03 \x01(\x0e2\x1e.wv2ray.plugin.ConfigFieldTypeR\tfieldType\x12B\n" +
	"\n" +
	"value_type\x18\x04 \x01(\x0e2#.wv2ray.plugin.ConfigFieldValueTypeR\tvalueType\x125\n" +
	"\x05value\x18\x05 \x01(\v2\x1f.wv2ray.plugin.ConfigFieldValueR\x05value\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x125\n" +
	"\aoptions\x18\a \x03(\v2\x1b.wv2ray.plugin.SelectOptionR\aoptions\x12D\n" +
	"\rdefault_value\x18\b \x01(\v2\x1f.wv2ray.plugin.ConfigFieldValueR\fdefaultValue\"a\n" +
	"\x18ProtocolConfigProperties\x12E\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2%.wv2ray.plugin.ProtocolConfigPropertyR\n" +
	"properties\"{\n" +
	"\x14ProtocolConfigDetail\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12G\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2'.wv2ray.plugin.ProtocolConfigPropertiesR\n" +
	"properties\"W\n" +
	"\x12ProtocolConfigList\x12A\n" +
	"\tprotocols\x18\x01 \x03(\v2#.wv2ray.plugin.ProtocolConfigDetailR\tprotocols\"d\n" +
	"\x15BriefProtocolProperty\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.wv2ray.plugin.ConfigFieldValueR\x05value\"_\n" +
	"\x17BriefProtocolProperties\x12D\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2$.wv2ray.plugin.BriefProtocolPropertyR\n" +
	"properties*(\n" +
	"\x0fConfigFieldType\x12\t\n" +
	"\x05INPUT\x10\x00\x12\n" +
	"\n" +
	"\x06SELECT\x10\x01*>\n" +
	"\x14ConfigFieldValueType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\a\n" +
	"\x03INT\x10\x01\x12\b\n" +
	"\x04BOOL\x10\x02\x12\a\n" +
	"\x03MAP\x10\x03B\x15Z\x13wv2ray/proto/pluginb\x06proto3"

var (
	file_plugin_protocol_configuer_proto_rawDescOnce sync.Once
	file_plugin_protocol_configuer_proto_rawDescData []byte
)

func file_plugin_protocol_configuer_proto_rawDescGZIP() []byte {
	file_plugin_protocol_configuer_proto_rawDescOnce.Do(func() {
		file_plugin_protocol_configuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_protocol_configuer_proto_rawDesc), len(file_plugin_protocol_configuer_proto_rawDesc)))
	})
	return file_plugin_protocol_configuer_proto_rawDescData
}

var file_plugin_protocol_configuer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_protocol_configuer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_plugin_protocol_configuer_proto_goTypes = []any{
	(ConfigFieldType)(0),             // 0: wv2ray.plugin.ConfigFieldType
	(ConfigFieldValueType)(0),        // 1: wv2ray.plugin.ConfigFieldValueType
	(*ConfigFieldValue)(nil),         // 2: wv2ray.plugin.ConfigFieldValue
	(*SelectOption)(nil),             // 3: wv2ray.plugin.SelectOption
	(*ProtocolConfigProperty)(nil),   // 4: wv2ray.plugin.ProtocolConfigProperty
	(*ProtocolConfigProperties)(nil), // 5: wv2ray.plugin.ProtocolConfigProperties
	(*ProtocolConfigDetail)(nil),     // 6: wv2ray.plugin.ProtocolConfigDetail
	(*ProtocolConfigList)(nil),       // 7: wv2ray.plugin.ProtocolConfigList
	(*BriefProtocolProperty)(nil),    // 8: wv2ray.plugin.BriefProtocolProperty
	(*BriefProtocolProperties)(nil),  // 9: wv2ray.plugin.BriefProtocolProperties
	(*MapValue)(nil),                 // 10: wv2ray.plugin.MapValue
}
var file_plugin_protocol_configuer_proto_depIdxs = []int32{
	10, // 0: wv2ray.plugin.ConfigFieldValue.map_value:type_name -> wv2ray.plugin.MapValue
	0,  // 1: wv2ray.plugin.ProtocolConfigProperty.field_type:type_name -> wv2ray.plugin.ConfigFieldType
	1,  // 2: wv2ray.plugin.ProtocolConfigProperty.value_type:type_name -> wv2ray.plugin.ConfigFieldValueType
	2,  // 3: wv2ray.plugin.ProtocolConfigProperty.value:type_name -> wv2ray.plugin.ConfigFieldValue
	3,  // 4: wv2ray.plugin.ProtocolConfigProperty.options:type_name -> wv2ray.plugin.SelectOption
	2,  // 5: wv2ray.plugin.ProtocolConfigProperty.default_value:type_name -> wv2ray.plugin.ConfigFieldValue
	4,  // 6: wv2ray.plugin.ProtocolConfigProperties.properties:type_name -> wv2ray.plugin.ProtocolConfigProperty
	5,  // 7: wv2ray.plugin.ProtocolConfigDetail.properties:type_name -> wv2ray.plugin.ProtocolConfigProperties
	6,  // 8: wv2ray.plugin.ProtocolConfigList.protocols:type_name -> wv2ray.plugin.ProtocolConfigDetail
	2,  // 9: wv2ray.plugin.BriefProtocolProperty.value:type_name -> wv2ray.plugin.ConfigFieldValue
	8,  // 10: wv2ray.plugin.BriefProtocolProperties.properties:type_name -> wv2ray.plugin.BriefProtocolProperty
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_plugin_protocol_configuer_proto_init() }
func file_plugin_protocol_configuer_proto_init() {
	if File_plugin_protocol_configuer_proto != nil {
		return
	}
	file_plugin_common_proto_init()
	file_plugin_protocol_configuer_proto_msgTypes[0].OneofWrappers = []any{
		(*ConfigFieldValue_StrValue)(nil),
		(*ConfigFieldValue_IntValue)(nil),
		(*ConfigFieldValue_BoolValue)(nil),
		(*ConfigFieldValue_MapValue)(nil),
	}
	file_plugin_protocol_configuer_proto_msgTypes[1].OneofWrappers = []any{
		(*SelectOption_StrValue)(nil),
		(*SelectOption_IntValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_protocol_configuer_proto_rawDesc), len(file_plugin_protocol_configuer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_protocol_configuer_proto_goTypes,
		DependencyIndexes: file_plugin_protocol_configuer_proto_depIdxs,
		EnumInfos:         file_plugin_protocol_configuer_proto_enumTypes,
		MessageInfos:      file_plugin_protocol_configuer_proto_msgTypes,
	}.Build()
	File_plugin_protocol_configuer_proto = out.File
	file_plugin_protocol_configuer_proto_goTypes = nil
	file_plugin_protocol_configuer_proto_depIdxs = nil
}
