// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plugin/service.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Network defines the type of network protocol.
type Network int32

const (
	Network_NETWORK_TCP Network = 0
	Network_NETWORK_UDP Network = 1
)

// Enum value maps for Network.
var (
	Network_name = map[int32]string{
		0: "NETWORK_TCP",
		1: "NETWORK_UDP",
	}
	Network_value = map[string]int32{
		"NETWORK_TCP": 0,
		"NETWORK_UDP": 1,
	}
)

func (x Network) Enum() *Network {
	p := new(Network)
	*p = x
	return p
}

func (x Network) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Network) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_service_proto_enumTypes[0].Descriptor()
}

func (Network) Type() protoreflect.EnumType {
	return &file_plugin_service_proto_enumTypes[0]
}

func (x Network) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Network.Descriptor instead.
func (Network) EnumDescriptor() ([]byte, []int) {
	return file_plugin_service_proto_rawDescGZIP(), []int{0}
}

// EmptyRequest represents an empty request message.
type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_plugin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_service_proto_rawDescGZIP(), []int{0}
}

// EmptyResponse represents an empty response message.
type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_plugin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_service_proto_rawDescGZIP(), []int{1}
}

// PluginInfo represents information about a plugin.
type PluginInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author        string                  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Logo          []byte                  `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Description   string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                  `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Protocols     []*ProtocolConfigDetail `protobuf:"bytes,6,rep,name=protocols,proto3" json:"protocols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_service_proto_rawDescGZIP(), []int{2}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetLogo() []byte {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetProtocols() []*ProtocolConfigDetail {
	if x != nil {
		return x.Protocols
	}
	return nil
}

// NewHandlerRequest represents a request to create a new handler.
type NewHandlerRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocol      string                   `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Properties    []*BriefProtocolProperty `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewHandlerRequest) Reset() {
	*x = NewHandlerRequest{}
	mi := &file_plugin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewHandlerRequest) ProtoMessage() {}

func (x *NewHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewHandlerRequest.ProtoReflect.Descriptor instead.
func (*NewHandlerRequest) Descriptor() ([]byte, []int) {
	return file_plugin_service_proto_rawDescGZIP(), []int{3}
}

func (x *NewHandlerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewHandlerRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NewHandlerRequest) GetProperties() []*BriefProtocolProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

// SetLocaleRequest represents a request to set the locale.
type SetLocaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocaleRequest) Reset() {
	*x = SetLocaleRequest{}
	mi := &file_plugin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocaleRequest) ProtoMessage() {}

func (x *SetLocaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocaleRequest.ProtoReflect.Descriptor instead.
func (*SetLocaleRequest) Descriptor() ([]byte, []int) {
	return file_plugin_service_proto_rawDescGZIP(), []int{4}
}

func (x *SetLocaleRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// ShutdownHandlerRequest represents a request to shut down a handler.
type ShutdownHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownHandlerRequest) Reset() {
	*x = ShutdownHandlerRequest{}
	mi := &file_plugin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownHandlerRequest) ProtoMessage() {}

func (x *ShutdownHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownHandlerRequest.ProtoReflect.Descriptor instead.
func (*ShutdownHandlerRequest) Descriptor() ([]byte, []int) {
	return file_plugin_service_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownHandlerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// HandshakeData represents a chunk of handshake data.
type HandshakeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerId     string                 `protobuf:"bytes,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeData) Reset() {
	*x = HandshakeData{}
	mi := &file_plugin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeData) ProtoMessage() {}

func (x *HandshakeData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeData.ProtoReflect.Descriptor instead.
func (*HandshakeData) Descriptor() ([]byte, []int) {
	return file_plugin_service_proto_rawDescGZIP(), []int{6}
}

func (x *HandshakeData) GetHandlerId() string {
	if x != nil {
		return x.HandlerId
	}
	return ""
}

func (x *HandshakeData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HandshakeData) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// TransportData represents a chunk of transport data.
type TransportData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerId     string                 `protobuf:"bytes,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	Network       Network                `protobuf:"varint,2,opt,name=network,proto3,enum=wv2ray.plugin.Network" json:"network,omitempty"`
	DestAddr      string                 `protobuf:"bytes,3,opt,name=dest_addr,json=destAddr,proto3" json:"dest_addr,omitempty"`
	DestPort      uint64                 `protobuf:"varint,4,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportData) Reset() {
	*x = TransportData{}
	mi := &file_plugin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportData) ProtoMessage() {}

func (x *TransportData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportData.ProtoReflect.Descriptor instead.
func (*TransportData) Descriptor() ([]byte, []int) {
	return file_plugin_service_proto_rawDescGZIP(), []int{7}
}

func (x *TransportData) GetHandlerId() string {
	if x != nil {
		return x.HandlerId
	}
	return ""
}

func (x *TransportData) GetNetwork() Network {
	if x != nil {
		return x.Network
	}
	return Network_NETWORK_TCP
}

func (x *TransportData) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

func (x *TransportData) GetDestPort() uint64 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *TransportData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_plugin_service_proto protoreflect.FileDescriptor

const file_plugin_service_proto_rawDesc = "" +
	"\n" +
	"\x14plugin/service.proto\x12\rwv2ray.plugin\x1a\x1fplugin/protocol_configuer.proto\"\x0e\n" +
	"\fEmptyRequest\"\x0f\n" +
	"\rEmptyResponse\"\xcb\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\fR\x04logo\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12A\n" +
	"\tprotocols\x18\x06 \x03(\v2#.wv2ray.plugin.ProtocolConfigDetailR\tprotocols\"\x85\x01\n" +
	"\x11NewHandlerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12D\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2$.wv2ray.plugin.BriefProtocolPropertyR\n" +
	"properties\".\n" +
	"\x10SetLocaleRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\"(\n" +
	"\x16ShutdownHandlerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\rHandshakeData\x12\x1d\n" +
	"\n" +
	"handler_id\x18\x01 \x01(\tR\thandlerId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\"\xae\x01\n" +
	"\rTransportData\x12\x1d\n" +
	"\n" +
	"handler_id\x18\x01 \x01(\tR\thandlerId\x120\n" +
	"\anetwork\x18\x02 \x01(\x0e2\x16.wv2ray.plugin.NetworkR\anetwork\x12\x1b\n" +
	"\tdest_addr\x18\x03 \x01(\tR\bdestAddr\x12\x1b\n" +
	"\tdest_port\x18\x04 \x01(\x04R\bdestPort\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data*+\n" +
	"\aNetwork\x12\x0f\n" +
	"\vNETWORK_TCP\x10\x00\x12\x0f\n" +
	"\vNETWORK_UDP\x10\x012\xa0\x04\n" +
	"\x0ePluginOutbound\x12A\n" +
	"\aGetInfo\x12\x1b.wv2ray.plugin.EmptyRequest\x1a\x19.wv2ray.plugin.PluginInfo\x12A\n" +
	"\x04Init\x12\x1b.wv2ray.plugin.EmptyRequest\x1a\x1c.wv2ray.plugin.EmptyResponse\x12L\n" +
	"\n" +
	"NewHandler\x12 .wv2ray.plugin.NewHandlerRequest\x1a\x1c.wv2ray.plugin.EmptyResponse\x12J\n" +
	"\tSetLocale\x12\x1f.wv2ray.plugin.SetLocaleRequest\x1a\x1c.wv2ray.plugin.EmptyResponse\x12V\n" +
	"\x0fShutdownHandler\x12%.wv2ray.plugin.ShutdownHandlerRequest\x1a\x1c.wv2ray.plugin.EmptyResponse\x12K\n" +
	"\tHandshake\x12\x1c.wv2ray.plugin.HandshakeData\x1a\x1c.wv2ray.plugin.HandshakeData(\x010\x01\x12I\n" +
	"\aProcess\x12\x1c.wv2ray.plugin.TransportData\x1a\x1c.wv2ray.plugin.TransportData(\x010\x01B\x15Z\x13wv2ray/proto/pluginb\x06proto3"

var (
	file_plugin_service_proto_rawDescOnce sync.Once
	file_plugin_service_proto_rawDescData []byte
)

func file_plugin_service_proto_rawDescGZIP() []byte {
	file_plugin_service_proto_rawDescOnce.Do(func() {
		file_plugin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_service_proto_rawDesc), len(file_plugin_service_proto_rawDesc)))
	})
	return file_plugin_service_proto_rawDescData
}

var file_plugin_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_plugin_service_proto_goTypes = []any{
	(Network)(0),                   // 0: wv2ray.plugin.Network
	(*EmptyRequest)(nil),           // 1: wv2ray.plugin.EmptyRequest
	(*EmptyResponse)(nil),          // 2: wv2ray.plugin.EmptyResponse
	(*PluginInfo)(nil),             // 3: wv2ray.plugin.PluginInfo
	(*NewHandlerRequest)(nil),      // 4: wv2ray.plugin.NewHandlerRequest
	(*SetLocaleRequest)(nil),       // 5: wv2ray.plugin.SetLocaleRequest
	(*ShutdownHandlerRequest)(nil), // 6: wv2ray.plugin.ShutdownHandlerRequest
	(*HandshakeData)(nil),          // 7: wv2ray.plugin.HandshakeData
	(*TransportData)(nil),          // 8: wv2ray.plugin.TransportData
	(*ProtocolConfigDetail)(nil),   // 9: wv2ray.plugin.ProtocolConfigDetail
	(*BriefProtocolProperty)(nil),  // 10: wv2ray.plugin.BriefProtocolProperty
}
var file_plugin_service_proto_depIdxs = []int32{
	9,  // 0: wv2ray.plugin.PluginInfo.protocols:type_name -> wv2ray.plugin.ProtocolConfigDetail
	10, // 1: wv2ray.plugin.NewHandlerRequest.properties:type_name -> wv2ray.plugin.BriefProtocolProperty
	0,  // 2: wv2ray.plugin.TransportData.network:type_name -> wv2ray.plugin.Network
	1,  // 3: wv2ray.plugin.PluginOutbound.GetInfo:input_type -> wv2ray.plugin.EmptyRequest
	1,  // 4: wv2ray.plugin.PluginOutbound.Init:input_type -> wv2ray.plugin.EmptyRequest
	4,  // 5: wv2ray.plugin.PluginOutbound.NewHandler:input_type -> wv2ray.plugin.NewHandlerRequest
	5,  // 6: wv2ray.plugin.PluginOutbound.SetLocale:input_type -> wv2ray.plugin.SetLocaleRequest
	6,  // 7: wv2ray.plugin.PluginOutbound.ShutdownHandler:input_type -> wv2ray.plugin.ShutdownHandlerRequest
	7,  // 8: wv2ray.plugin.PluginOutbound.Handshake:input_type -> wv2ray.plugin.HandshakeData
	8,  // 9: wv2ray.plugin.PluginOutbound.Process:input_type -> wv2ray.plugin.TransportData
	3,  // 10: wv2ray.plugin.PluginOutbound.GetInfo:output_type -> wv2ray.plugin.PluginInfo
	2,  // 11: wv2ray.plugin.PluginOutbound.Init:output_type -> wv2ray.plugin.EmptyResponse
	2,  // 12: wv2ray.plugin.PluginOutbound.NewHandler:output_type -> wv2ray.plugin.EmptyResponse
	2,  // 13: wv2ray.plugin.PluginOutbound.SetLocale:output_type -> wv2ray.plugin.EmptyResponse
	2,  // 14: wv2ray.plugin.PluginOutbound.ShutdownHandler:output_type -> wv2ray.plugin.EmptyResponse
	7,  // 15: wv2ray.plugin.PluginOutbound.Handshake:output_type -> wv2ray.plugin.HandshakeData
	8,  // 16: wv2ray.plugin.PluginOutbound.Process:output_type -> wv2ray.plugin.TransportData
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_service_proto_init() }
func file_plugin_service_proto_init() {
	if File_plugin_service_proto != nil {
		return
	}
	file_plugin_protocol_configuer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_service_proto_rawDesc), len(file_plugin_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_service_proto_goTypes,
		DependencyIndexes: file_plugin_service_proto_depIdxs,
		EnumInfos:         file_plugin_service_proto_enumTypes,
		MessageInfos:      file_plugin_service_proto_msgTypes,
	}.Build()
	File_plugin_service_proto = out.File
	file_plugin_service_proto_goTypes = nil
	file_plugin_service_proto_depIdxs = nil
}
