// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: plugin/service.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginOutbound_GetInfo_FullMethodName         = "/wv2ray.plugin.PluginOutbound/GetInfo"
	PluginOutbound_Init_FullMethodName            = "/wv2ray.plugin.PluginOutbound/Init"
	PluginOutbound_NewHandler_FullMethodName      = "/wv2ray.plugin.PluginOutbound/NewHandler"
	PluginOutbound_SetLocale_FullMethodName       = "/wv2ray.plugin.PluginOutbound/SetLocale"
	PluginOutbound_ShutdownHandler_FullMethodName = "/wv2ray.plugin.PluginOutbound/ShutdownHandler"
	PluginOutbound_Handshake_FullMethodName       = "/wv2ray.plugin.PluginOutbound/Handshake"
	PluginOutbound_Process_FullMethodName         = "/wv2ray.plugin.PluginOutbound/Process"
)

// PluginOutboundClient is the client API for PluginOutbound service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginOutbound defines the outbound plugin service.
type PluginOutboundClient interface {
	// GetInfo retrieves information about the plugin.
	GetInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*PluginInfo, error)
	// Init initializes the plugin.
	Init(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// NewHandler creates a new handler with the given protocol properties.
	NewHandler(ctx context.Context, in *NewHandlerRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// SetLocale sets the locale for the plugin.
	SetLocale(ctx context.Context, in *SetLocaleRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// ShutdownHandler shuts down the handler with the specified ID.
	ShutdownHandler(ctx context.Context, in *ShutdownHandlerRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Handshake performs a handshake for streaming data.
	Handshake(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandshakeData, HandshakeData], error)
	// Process processes streaming data.
	Process(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransportData, TransportData], error)
}

type pluginOutboundClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginOutboundClient(cc grpc.ClientConnInterface) PluginOutboundClient {
	return &pluginOutboundClient{cc}
}

func (c *pluginOutboundClient) GetInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, PluginOutbound_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginOutboundClient) Init(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, PluginOutbound_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginOutboundClient) NewHandler(ctx context.Context, in *NewHandlerRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, PluginOutbound_NewHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginOutboundClient) SetLocale(ctx context.Context, in *SetLocaleRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, PluginOutbound_SetLocale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginOutboundClient) ShutdownHandler(ctx context.Context, in *ShutdownHandlerRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, PluginOutbound_ShutdownHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginOutboundClient) Handshake(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandshakeData, HandshakeData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginOutbound_ServiceDesc.Streams[0], PluginOutbound_Handshake_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HandshakeData, HandshakeData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginOutbound_HandshakeClient = grpc.BidiStreamingClient[HandshakeData, HandshakeData]

func (c *pluginOutboundClient) Process(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransportData, TransportData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginOutbound_ServiceDesc.Streams[1], PluginOutbound_Process_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransportData, TransportData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginOutbound_ProcessClient = grpc.BidiStreamingClient[TransportData, TransportData]

// PluginOutboundServer is the server API for PluginOutbound service.
// All implementations must embed UnimplementedPluginOutboundServer
// for forward compatibility.
//
// PluginOutbound defines the outbound plugin service.
type PluginOutboundServer interface {
	// GetInfo retrieves information about the plugin.
	GetInfo(context.Context, *EmptyRequest) (*PluginInfo, error)
	// Init initializes the plugin.
	Init(context.Context, *EmptyRequest) (*EmptyResponse, error)
	// NewHandler creates a new handler with the given protocol properties.
	NewHandler(context.Context, *NewHandlerRequest) (*EmptyResponse, error)
	// SetLocale sets the locale for the plugin.
	SetLocale(context.Context, *SetLocaleRequest) (*EmptyResponse, error)
	// ShutdownHandler shuts down the handler with the specified ID.
	ShutdownHandler(context.Context, *ShutdownHandlerRequest) (*EmptyResponse, error)
	// Handshake performs a handshake for streaming data.
	Handshake(grpc.BidiStreamingServer[HandshakeData, HandshakeData]) error
	// Process processes streaming data.
	Process(grpc.BidiStreamingServer[TransportData, TransportData]) error
	mustEmbedUnimplementedPluginOutboundServer()
}

// UnimplementedPluginOutboundServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginOutboundServer struct{}

func (UnimplementedPluginOutboundServer) GetInfo(context.Context, *EmptyRequest) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPluginOutboundServer) Init(context.Context, *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPluginOutboundServer) NewHandler(context.Context, *NewHandlerRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewHandler not implemented")
}
func (UnimplementedPluginOutboundServer) SetLocale(context.Context, *SetLocaleRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLocale not implemented")
}
func (UnimplementedPluginOutboundServer) ShutdownHandler(context.Context, *ShutdownHandlerRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShutdownHandler not implemented")
}
func (UnimplementedPluginOutboundServer) Handshake(grpc.BidiStreamingServer[HandshakeData, HandshakeData]) error {
	return status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedPluginOutboundServer) Process(grpc.BidiStreamingServer[TransportData, TransportData]) error {
	return status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedPluginOutboundServer) mustEmbedUnimplementedPluginOutboundServer() {}
func (UnimplementedPluginOutboundServer) testEmbeddedByValue()                        {}

// UnsafePluginOutboundServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginOutboundServer will
// result in compilation errors.
type UnsafePluginOutboundServer interface {
	mustEmbedUnimplementedPluginOutboundServer()
}

func RegisterPluginOutboundServer(s grpc.ServiceRegistrar, srv PluginOutboundServer) {
	// If the following call panics, it indicates UnimplementedPluginOutboundServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginOutbound_ServiceDesc, srv)
}

func _PluginOutbound_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginOutboundServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginOutbound_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginOutboundServer).GetInfo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginOutbound_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginOutboundServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginOutbound_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginOutboundServer).Init(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginOutbound_NewHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginOutboundServer).NewHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginOutbound_NewHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginOutboundServer).NewHandler(ctx, req.(*NewHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginOutbound_SetLocale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLocaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginOutboundServer).SetLocale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginOutbound_SetLocale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginOutboundServer).SetLocale(ctx, req.(*SetLocaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginOutbound_ShutdownHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginOutboundServer).ShutdownHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginOutbound_ShutdownHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginOutboundServer).ShutdownHandler(ctx, req.(*ShutdownHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginOutbound_Handshake_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginOutboundServer).Handshake(&grpc.GenericServerStream[HandshakeData, HandshakeData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginOutbound_HandshakeServer = grpc.BidiStreamingServer[HandshakeData, HandshakeData]

func _PluginOutbound_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginOutboundServer).Process(&grpc.GenericServerStream[TransportData, TransportData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginOutbound_ProcessServer = grpc.BidiStreamingServer[TransportData, TransportData]

// PluginOutbound_ServiceDesc is the grpc.ServiceDesc for PluginOutbound service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginOutbound_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wv2ray.plugin.PluginOutbound",
	HandlerType: (*PluginOutboundServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PluginOutbound_GetInfo_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _PluginOutbound_Init_Handler,
		},
		{
			MethodName: "NewHandler",
			Handler:    _PluginOutbound_NewHandler_Handler,
		},
		{
			MethodName: "SetLocale",
			Handler:    _PluginOutbound_SetLocale_Handler,
		},
		{
			MethodName: "ShutdownHandler",
			Handler:    _PluginOutbound_ShutdownHandler_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Handshake",
			Handler:       _PluginOutbound_Handshake_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Process",
			Handler:       _PluginOutbound_Process_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin/service.proto",
}
