// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plugin/stream_setting.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamNetWork defines the type of network for stream settings.
type StreamNetWork int32

const (
	StreamNetWork_TCP  StreamNetWork = 0
	StreamNetWork_KCP  StreamNetWork = 1
	StreamNetWork_GRPC StreamNetWork = 2
	StreamNetWork_WS   StreamNetWork = 3
)

// Enum value maps for StreamNetWork.
var (
	StreamNetWork_name = map[int32]string{
		0: "TCP",
		1: "KCP",
		2: "GRPC",
		3: "WS",
	}
	StreamNetWork_value = map[string]int32{
		"TCP":  0,
		"KCP":  1,
		"GRPC": 2,
		"WS":   3,
	}
)

func (x StreamNetWork) Enum() *StreamNetWork {
	p := new(StreamNetWork)
	*p = x
	return p
}

func (x StreamNetWork) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamNetWork) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_stream_setting_proto_enumTypes[0].Descriptor()
}

func (StreamNetWork) Type() protoreflect.EnumType {
	return &file_plugin_stream_setting_proto_enumTypes[0]
}

func (x StreamNetWork) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamNetWork.Descriptor instead.
func (StreamNetWork) EnumDescriptor() ([]byte, []int) {
	return file_plugin_stream_setting_proto_rawDescGZIP(), []int{0}
}

// CertificateUsage defines the usage type of a certificate.
type CertificateUsage int32

const (
	CertificateUsage_ENCIPHERMENT CertificateUsage = 0
	CertificateUsage_VERIFY       CertificateUsage = 1
	CertificateUsage_ISSUE        CertificateUsage = 2
)

// Enum value maps for CertificateUsage.
var (
	CertificateUsage_name = map[int32]string{
		0: "ENCIPHERMENT",
		1: "VERIFY",
		2: "ISSUE",
	}
	CertificateUsage_value = map[string]int32{
		"ENCIPHERMENT": 0,
		"VERIFY":       1,
		"ISSUE":        2,
	}
)

func (x CertificateUsage) Enum() *CertificateUsage {
	p := new(CertificateUsage)
	*p = x
	return p
}

func (x CertificateUsage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateUsage) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_stream_setting_proto_enumTypes[1].Descriptor()
}

func (CertificateUsage) Type() protoreflect.EnumType {
	return &file_plugin_stream_setting_proto_enumTypes[1]
}

func (x CertificateUsage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateUsage.Descriptor instead.
func (CertificateUsage) EnumDescriptor() ([]byte, []int) {
	return file_plugin_stream_setting_proto_rawDescGZIP(), []int{1}
}

// StreamTCPSetting represents TCP-specific stream settings.
type StreamTCPSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTCPSetting) Reset() {
	*x = StreamTCPSetting{}
	mi := &file_plugin_stream_setting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTCPSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTCPSetting) ProtoMessage() {}

func (x *StreamTCPSetting) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_stream_setting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTCPSetting.ProtoReflect.Descriptor instead.
func (*StreamTCPSetting) Descriptor() ([]byte, []int) {
	return file_plugin_stream_setting_proto_rawDescGZIP(), []int{0}
}

// StreamKCPSetting represents KCP-specific stream settings.
type StreamKCPSetting struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mtu              int64                  `protobuf:"varint,1,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Tti              int64                  `protobuf:"varint,2,opt,name=tti,proto3" json:"tti,omitempty"`
	UplinkCapacity   int64                  `protobuf:"varint,3,opt,name=uplink_capacity,json=uplinkCapacity,proto3" json:"uplink_capacity,omitempty"`
	DownlinkCapacity int64                  `protobuf:"varint,4,opt,name=downlink_capacity,json=downlinkCapacity,proto3" json:"downlink_capacity,omitempty"`
	Congestion       bool                   `protobuf:"varint,5,opt,name=congestion,proto3" json:"congestion,omitempty"`
	ReadBufferSize   int64                  `protobuf:"varint,6,opt,name=read_buffer_size,json=readBufferSize,proto3" json:"read_buffer_size,omitempty"`
	WriteBufferSize  int64                  `protobuf:"varint,7,opt,name=write_buffer_size,json=writeBufferSize,proto3" json:"write_buffer_size,omitempty"`
	HeaderType       string                 `protobuf:"bytes,8,opt,name=header_type,json=headerType,proto3" json:"header_type,omitempty"`
	HeaderDomain     string                 `protobuf:"bytes,9,opt,name=header_domain,json=headerDomain,proto3" json:"header_domain,omitempty"`
	Seed             string                 `protobuf:"bytes,10,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamKCPSetting) Reset() {
	*x = StreamKCPSetting{}
	mi := &file_plugin_stream_setting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamKCPSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamKCPSetting) ProtoMessage() {}

func (x *StreamKCPSetting) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_stream_setting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamKCPSetting.ProtoReflect.Descriptor instead.
func (*StreamKCPSetting) Descriptor() ([]byte, []int) {
	return file_plugin_stream_setting_proto_rawDescGZIP(), []int{1}
}

func (x *StreamKCPSetting) GetMtu() int64 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *StreamKCPSetting) GetTti() int64 {
	if x != nil {
		return x.Tti
	}
	return 0
}

func (x *StreamKCPSetting) GetUplinkCapacity() int64 {
	if x != nil {
		return x.UplinkCapacity
	}
	return 0
}

func (x *StreamKCPSetting) GetDownlinkCapacity() int64 {
	if x != nil {
		return x.DownlinkCapacity
	}
	return 0
}

func (x *StreamKCPSetting) GetCongestion() bool {
	if x != nil {
		return x.Congestion
	}
	return false
}

func (x *StreamKCPSetting) GetReadBufferSize() int64 {
	if x != nil {
		return x.ReadBufferSize
	}
	return 0
}

func (x *StreamKCPSetting) GetWriteBufferSize() int64 {
	if x != nil {
		return x.WriteBufferSize
	}
	return 0
}

func (x *StreamKCPSetting) GetHeaderType() string {
	if x != nil {
		return x.HeaderType
	}
	return ""
}

func (x *StreamKCPSetting) GetHeaderDomain() string {
	if x != nil {
		return x.HeaderDomain
	}
	return ""
}

func (x *StreamKCPSetting) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

// StreamGrpcSetting represents gRPC-specific stream settings.
type StreamGrpcSetting struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Authority           string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	ServiceName         string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	UserAgent           string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IdleTimeout         int64                  `protobuf:"varint,4,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	HealthCheckTimeout  int64                  `protobuf:"varint,5,opt,name=health_check_timeout,json=healthCheckTimeout,proto3" json:"health_check_timeout,omitempty"`
	PermitWithoutStream bool                   `protobuf:"varint,6,opt,name=permit_without_stream,json=permitWithoutStream,proto3" json:"permit_without_stream,omitempty"`
	InitialWindowsSize  int64                  `protobuf:"varint,7,opt,name=initial_windows_size,json=initialWindowsSize,proto3" json:"initial_windows_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamGrpcSetting) Reset() {
	*x = StreamGrpcSetting{}
	mi := &file_plugin_stream_setting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamGrpcSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGrpcSetting) ProtoMessage() {}

func (x *StreamGrpcSetting) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_stream_setting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGrpcSetting.ProtoReflect.Descriptor instead.
func (*StreamGrpcSetting) Descriptor() ([]byte, []int) {
	return file_plugin_stream_setting_proto_rawDescGZIP(), []int{2}
}

func (x *StreamGrpcSetting) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *StreamGrpcSetting) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StreamGrpcSetting) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *StreamGrpcSetting) GetIdleTimeout() int64 {
	if x != nil {
		return x.IdleTimeout
	}
	return 0
}

func (x *StreamGrpcSetting) GetHealthCheckTimeout() int64 {
	if x != nil {
		return x.HealthCheckTimeout
	}
	return 0
}

func (x *StreamGrpcSetting) GetPermitWithoutStream() bool {
	if x != nil {
		return x.PermitWithoutStream
	}
	return false
}

func (x *StreamGrpcSetting) GetInitialWindowsSize() int64 {
	if x != nil {
		return x.InitialWindowsSize
	}
	return 0
}

// StreamWSSetting represents WebSocket-specific stream settings.
type StreamWSSetting struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Path            string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Host            string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Headers         *MapValue              `protobuf:"bytes,3,opt,name=headers,proto3" json:"headers,omitempty"`
	HeartbeatPeriod int64                  `protobuf:"varint,4,opt,name=heartbeat_period,json=heartbeatPeriod,proto3" json:"heartbeat_period,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamWSSetting) Reset() {
	*x = StreamWSSetting{}
	mi := &file_plugin_stream_setting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWSSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWSSetting) ProtoMessage() {}

func (x *StreamWSSetting) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_stream_setting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWSSetting.ProtoReflect.Descriptor instead.
func (*StreamWSSetting) Descriptor() ([]byte, []int) {
	return file_plugin_stream_setting_proto_rawDescGZIP(), []int{3}
}

func (x *StreamWSSetting) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StreamWSSetting) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *StreamWSSetting) GetHeaders() *MapValue {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *StreamWSSetting) GetHeartbeatPeriod() int64 {
	if x != nil {
		return x.HeartbeatPeriod
	}
	return 0
}

// ServerCertificate represents a server certificate for TLS settings.
type ServerCertificate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OcspStapling    int64                  `protobuf:"varint,1,opt,name=ocsp_stapling,json=ocspStapling,proto3" json:"ocsp_stapling,omitempty"`
	OneTimeLoading  bool                   `protobuf:"varint,2,opt,name=one_time_loading,json=oneTimeLoading,proto3" json:"one_time_loading,omitempty"`
	Usage           CertificateUsage       `protobuf:"varint,3,opt,name=usage,proto3,enum=wv2ray.plugin.CertificateUsage" json:"usage,omitempty"`
	CertificateFile string                 `protobuf:"bytes,4,opt,name=certificate_file,json=certificateFile,proto3" json:"certificate_file,omitempty"`
	KeyFile         string                 `protobuf:"bytes,5,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerCertificate) Reset() {
	*x = ServerCertificate{}
	mi := &file_plugin_stream_setting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCertificate) ProtoMessage() {}

func (x *ServerCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_stream_setting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCertificate.ProtoReflect.Descriptor instead.
func (*ServerCertificate) Descriptor() ([]byte, []int) {
	return file_plugin_stream_setting_proto_rawDescGZIP(), []int{4}
}

func (x *ServerCertificate) GetOcspStapling() int64 {
	if x != nil {
		return x.OcspStapling
	}
	return 0
}

func (x *ServerCertificate) GetOneTimeLoading() bool {
	if x != nil {
		return x.OneTimeLoading
	}
	return false
}

func (x *ServerCertificate) GetUsage() CertificateUsage {
	if x != nil {
		return x.Usage
	}
	return CertificateUsage_ENCIPHERMENT
}

func (x *ServerCertificate) GetCertificateFile() string {
	if x != nil {
		return x.CertificateFile
	}
	return ""
}

func (x *ServerCertificate) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

// StreamTLSSetting represents TLS-specific stream settings.
type StreamTLSSetting struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServerName            string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	VerifyPeerCertInNames []string               `protobuf:"bytes,2,rep,name=verify_peer_cert_in_names,json=verifyPeerCertInNames,proto3" json:"verify_peer_cert_in_names,omitempty"`
	Alpn                  []string               `protobuf:"bytes,3,rep,name=alpn,proto3" json:"alpn,omitempty"`
	MinVersion            string                 `protobuf:"bytes,4,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MaxVersion            string                 `protobuf:"bytes,5,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"`
	CipherSuites          []string               `protobuf:"bytes,6,rep,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`
	AllowInsecure         bool                   `protobuf:"varint,7,opt,name=allow_insecure,json=allowInsecure,proto3" json:"allow_insecure,omitempty"`
	DisableSystemRoot     bool                   `protobuf:"varint,8,opt,name=disable_system_root,json=disableSystemRoot,proto3" json:"disable_system_root,omitempty"`
	Fingerprint           string                 `protobuf:"bytes,9,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Certificates          []*ServerCertificate   `protobuf:"bytes,10,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StreamTLSSetting) Reset() {
	*x = StreamTLSSetting{}
	mi := &file_plugin_stream_setting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTLSSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTLSSetting) ProtoMessage() {}

func (x *StreamTLSSetting) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_stream_setting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTLSSetting.ProtoReflect.Descriptor instead.
func (*StreamTLSSetting) Descriptor() ([]byte, []int) {
	return file_plugin_stream_setting_proto_rawDescGZIP(), []int{5}
}

func (x *StreamTLSSetting) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *StreamTLSSetting) GetVerifyPeerCertInNames() []string {
	if x != nil {
		return x.VerifyPeerCertInNames
	}
	return nil
}

func (x *StreamTLSSetting) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *StreamTLSSetting) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *StreamTLSSetting) GetMaxVersion() string {
	if x != nil {
		return x.MaxVersion
	}
	return ""
}

func (x *StreamTLSSetting) GetCipherSuites() []string {
	if x != nil {
		return x.CipherSuites
	}
	return nil
}

func (x *StreamTLSSetting) GetAllowInsecure() bool {
	if x != nil {
		return x.AllowInsecure
	}
	return false
}

func (x *StreamTLSSetting) GetDisableSystemRoot() bool {
	if x != nil {
		return x.DisableSystemRoot
	}
	return false
}

func (x *StreamTLSSetting) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *StreamTLSSetting) GetCertificates() []*ServerCertificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

// StreamSettings represents the stream settings for a connection.
type StreamSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       StreamNetWork          `protobuf:"varint,1,opt,name=network,proto3,enum=wv2ray.plugin.StreamNetWork" json:"network,omitempty"`
	Security      string                 `protobuf:"bytes,2,opt,name=security,proto3" json:"security,omitempty"`
	Tls           *StreamTLSSetting      `protobuf:"bytes,3,opt,name=tls,proto3" json:"tls,omitempty"`
	Tcp           *StreamTCPSetting      `protobuf:"bytes,4,opt,name=tcp,proto3" json:"tcp,omitempty"`
	Kcp           *StreamKCPSetting      `protobuf:"bytes,5,opt,name=kcp,proto3" json:"kcp,omitempty"`
	Grpc          *StreamGrpcSetting     `protobuf:"bytes,6,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Ws            *StreamWSSetting       `protobuf:"bytes,7,opt,name=ws,proto3" json:"ws,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSettings) Reset() {
	*x = StreamSettings{}
	mi := &file_plugin_stream_setting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSettings) ProtoMessage() {}

func (x *StreamSettings) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_stream_setting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSettings.ProtoReflect.Descriptor instead.
func (*StreamSettings) Descriptor() ([]byte, []int) {
	return file_plugin_stream_setting_proto_rawDescGZIP(), []int{6}
}

func (x *StreamSettings) GetNetwork() StreamNetWork {
	if x != nil {
		return x.Network
	}
	return StreamNetWork_TCP
}

func (x *StreamSettings) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *StreamSettings) GetTls() *StreamTLSSetting {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *StreamSettings) GetTcp() *StreamTCPSetting {
	if x != nil {
		return x.Tcp
	}
	return nil
}

func (x *StreamSettings) GetKcp() *StreamKCPSetting {
	if x != nil {
		return x.Kcp
	}
	return nil
}

func (x *StreamSettings) GetGrpc() *StreamGrpcSetting {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *StreamSettings) GetWs() *StreamWSSetting {
	if x != nil {
		return x.Ws
	}
	return nil
}

var File_plugin_stream_setting_proto protoreflect.FileDescriptor

const file_plugin_stream_setting_proto_rawDesc = "" +
	"\n" +
	"\x1bplugin/stream_setting.proto\x12\rwv2ray.plugin\x1a\x13plugin/common.proto\"\x12\n" +
	"\x10StreamTCPSetting\"\xdc\x02\n" +
	"\x10StreamKCPSetting\x12\x10\n" +
	"\x03mtu\x18\x01 \x01(\x03R\x03mtu\x12\x10\n" +
	"\x03tti\x18\x02 \x01(\x03R\x03tti\x12'\n" +
	"\x0fuplink_capacity\x18\x03 \x01(\x03R\x0euplinkCapacity\x12+\n" +
	"\x11downlink_capacity\x18\x04 \x01(\x03R\x10downlinkCapacity\x12\x1e\n" +
	"\n" +
	"congestion\x18\x05 \x01(\bR\n" +
	"congestion\x12(\n" +
	"\x10read_buffer_size\x18\x06 \x01(\x03R\x0ereadBufferSize\x12*\n" +
	"\x11write_buffer_size\x18\a \x01(\x03R\x0fwriteBufferSize\x12\x1f\n" +
	"\vheader_type\x18\b \x01(\tR\n" +
	"headerType\x12#\n" +
	"\rheader_domain\x18\t \x01(\tR\fheaderDomain\x12\x12\n" +
	"\x04seed\x18\n" +
	" \x01(\tR\x04seed\"\xae\x02\n" +
	"\x11StreamGrpcSetting\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12!\n" +
	"\fidle_timeout\x18\x04 \x01(\x03R\vidleTimeout\x120\n" +
	"\x14health_check_timeout\x18\x05 \x01(\x03R\x12healthCheckTimeout\x122\n" +
	"\x15permit_without_stream\x18\x06 \x01(\bR\x13permitWithoutStream\x120\n" +
	"\x14initial_windows_size\x18\a \x01(\x03R\x12initialWindowsSize\"\x97\x01\n" +
	"\x0fStreamWSSetting\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x121\n" +
	"\aheaders\x18\x03 \x01(\v2\x17.wv2ray.plugin.MapValueR\aheaders\x12)\n" +
	"\x10heartbeat_period\x18\x04 \x01(\x03R\x0fheartbeatPeriod\"\xdf\x01\n" +
	"\x11ServerCertificate\x12#\n" +
	"\rocsp_stapling\x18\x01 \x01(\x03R\focspStapling\x12(\n" +
	"\x10one_time_loading\x18\x02 \x01(\bR\x0eoneTimeLoading\x125\n" +
	"\x05usage\x18\x03 \x01(\x0e2\x1f.wv2ray.plugin.CertificateUsageR\x05usage\x12)\n" +
	"\x10certificate_file\x18\x04 \x01(\tR\x0fcertificateFile\x12\x19\n" +
	"\bkey_file\x18\x05 \x01(\tR\akeyFile\"\xa7\x03\n" +
	"\x10StreamTLSSetting\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x128\n" +
	"\x19verify_peer_cert_in_names\x18\x02 \x03(\tR\x15verifyPeerCertInNames\x12\x12\n" +
	"\x04alpn\x18\x03 \x03(\tR\x04alpn\x12\x1f\n" +
	"\vmin_version\x18\x04 \x01(\tR\n" +
	"minVersion\x12\x1f\n" +
	"\vmax_version\x18\x05 \x01(\tR\n" +
	"maxVersion\x12#\n" +
	"\rcipher_suites\x18\x06 \x03(\tR\fcipherSuites\x12%\n" +
	"\x0eallow_insecure\x18\a \x01(\bR\rallowInsecure\x12.\n" +
	"\x13disable_system_root\x18\b \x01(\bR\x11disableSystemRoot\x12 \n" +
	"\vfingerprint\x18\t \x01(\tR\vfingerprint\x12D\n" +
	"\fcertificates\x18\n" +
	" \x03(\v2 .wv2ray.plugin.ServerCertificateR\fcertificates\"\xe3\x02\n" +
	"\x0eStreamSettings\x126\n" +
	"\anetwork\x18\x01 \x01(\x0e2\x1c.wv2ray.plugin.StreamNetWorkR\anetwork\x12\x1a\n" +
	"\bsecurity\x18\x02 \x01(\tR\bsecurity\x121\n" +
	"\x03tls\x18\x03 \x01(\v2\x1f.wv2ray.plugin.StreamTLSSettingR\x03tls\x121\n" +
	"\x03tcp\x18\x04 \x01(\v2\x1f.wv2ray.plugin.StreamTCPSettingR\x03tcp\x121\n" +
	"\x03kcp\x18\x05 \x01(\v2\x1f.wv2ray.plugin.StreamKCPSettingR\x03kcp\x124\n" +
	"\x04grpc\x18\x06 \x01(\v2 .wv2ray.plugin.StreamGrpcSettingR\x04grpc\x12.\n" +
	"\x02ws\x18\a \x01(\v2\x1e.wv2ray.plugin.StreamWSSettingR\x02ws*3\n" +
	"\rStreamNetWork\x12\a\n" +
	"\x03TCP\x10\x00\x12\a\n" +
	"\x03KCP\x10\x01\x12\b\n" +
	"\x04GRPC\x10\x02\x12\x06\n" +
	"\x02WS\x10\x03*;\n" +
	"\x10CertificateUsage\x12\x10\n" +
	"\fENCIPHERMENT\x10\x00\x12\n" +
	"\n" +
	"\x06VERIFY\x10\x01\x12\t\n" +
	"\x05ISSUE\x10\x02B\x15Z\x13wv2ray/proto/pluginb\x06proto3"

var (
	file_plugin_stream_setting_proto_rawDescOnce sync.Once
	file_plugin_stream_setting_proto_rawDescData []byte
)

func file_plugin_stream_setting_proto_rawDescGZIP() []byte {
	file_plugin_stream_setting_proto_rawDescOnce.Do(func() {
		file_plugin_stream_setting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_stream_setting_proto_rawDesc), len(file_plugin_stream_setting_proto_rawDesc)))
	})
	return file_plugin_stream_setting_proto_rawDescData
}

var file_plugin_stream_setting_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_stream_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_plugin_stream_setting_proto_goTypes = []any{
	(StreamNetWork)(0),        // 0: wv2ray.plugin.StreamNetWork
	(CertificateUsage)(0),     // 1: wv2ray.plugin.CertificateUsage
	(*StreamTCPSetting)(nil),  // 2: wv2ray.plugin.StreamTCPSetting
	(*StreamKCPSetting)(nil),  // 3: wv2ray.plugin.StreamKCPSetting
	(*StreamGrpcSetting)(nil), // 4: wv2ray.plugin.StreamGrpcSetting
	(*StreamWSSetting)(nil),   // 5: wv2ray.plugin.StreamWSSetting
	(*ServerCertificate)(nil), // 6: wv2ray.plugin.ServerCertificate
	(*StreamTLSSetting)(nil),  // 7: wv2ray.plugin.StreamTLSSetting
	(*StreamSettings)(nil),    // 8: wv2ray.plugin.StreamSettings
	(*MapValue)(nil),          // 9: wv2ray.plugin.MapValue
}
var file_plugin_stream_setting_proto_depIdxs = []int32{
	9, // 0: wv2ray.plugin.StreamWSSetting.headers:type_name -> wv2ray.plugin.MapValue
	1, // 1: wv2ray.plugin.ServerCertificate.usage:type_name -> wv2ray.plugin.CertificateUsage
	6, // 2: wv2ray.plugin.StreamTLSSetting.certificates:type_name -> wv2ray.plugin.ServerCertificate
	0, // 3: wv2ray.plugin.StreamSettings.network:type_name -> wv2ray.plugin.StreamNetWork
	7, // 4: wv2ray.plugin.StreamSettings.tls:type_name -> wv2ray.plugin.StreamTLSSetting
	2, // 5: wv2ray.plugin.StreamSettings.tcp:type_name -> wv2ray.plugin.StreamTCPSetting
	3, // 6: wv2ray.plugin.StreamSettings.kcp:type_name -> wv2ray.plugin.StreamKCPSetting
	4, // 7: wv2ray.plugin.StreamSettings.grpc:type_name -> wv2ray.plugin.StreamGrpcSetting
	5, // 8: wv2ray.plugin.StreamSettings.ws:type_name -> wv2ray.plugin.StreamWSSetting
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_plugin_stream_setting_proto_init() }
func file_plugin_stream_setting_proto_init() {
	if File_plugin_stream_setting_proto != nil {
		return
	}
	file_plugin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_stream_setting_proto_rawDesc), len(file_plugin_stream_setting_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_stream_setting_proto_goTypes,
		DependencyIndexes: file_plugin_stream_setting_proto_depIdxs,
		EnumInfos:         file_plugin_stream_setting_proto_enumTypes,
		MessageInfos:      file_plugin_stream_setting_proto_msgTypes,
	}.Build()
	File_plugin_stream_setting_proto = out.File
	file_plugin_stream_setting_proto_goTypes = nil
	file_plugin_stream_setting_proto_depIdxs = nil
}
